name: Build Rock

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  build-rock:
    uses: canonical/oci-factory/.github/workflows/Build-Rock.yaml@631b6dde575075c167b77f71619777e27210926a
    with:
      rock-repo: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
      rock-repo-commit: ${{ github.head_ref || github.ref_name }}
      rockfile-directory: .
      oci-archive-name: api-demo-server-${{ github.head_ref || github.ref_name }}
