name: Integration test

on:
  push:
    branches: ["master"]
  pull_request:

permissions: {}

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install Rockcraft
        run: sudo snap install rockcraft --classic

      - name: Pack the rock
        run: rockcraft pack

      - name: Run the integration test
        run: make integration
